### ISSUE TITLE
Need some help to get it working

### ISSUE THREAD

**Issue by kas1kas** [Billiam/cncjs-pendant-keyboardreader#2]
This looks like a great utility and I really want to use it on my CNC, but it doesn't start correctly.
Here my issue, please help:

After I run: 

**bin/cncjs-pendant-keyboardreader --socket-port 8000 --port /dev/ttyACM0 --device /dev/hidraw0**

I see a constantly updating bunch of text with parameters of my CNC like this:

        plane: 'G17',
        units: 'G21',
        distance: 'G90',
        feedrate: 'G94',
        spindle: 'M5',
        coolant: 'M9' },
     tool: '0',
     feedrate: '0',
     spindle: '0' } }
state { status:
   { activeState: 'Idle',
     mpos: { x: '-40.000', y: '0.000', z: '0.000' },
     wpos: { x: '262.800', y: '232.000', z: '74.500' },
     ov: [ 100, 100, 100 ],
     subState: 0,
     wco: { x: '-302.800', y: '-232.000', z: '-74.500' },
     buf: { planner: 15, rx: 128 },
     feedrate: 0,
     spindle: 0 },
  parserstate:
   { modal:
      { motion: 'G0',
        wcs: 'G54',
        plane: 'G17',
        units: 'G21',
        distance: 'G90',
        feedrate: 'G94',
        spindle: 'M5',
        coolant: 'M9' },
     tool: '0',
     feedrate: '0',
     spindle: '0' } }
state { status:
   { activeState: 'Idle',
     mpos: { x: '-40.000', y: '0.000', z: '0.000' },
     wpos: { x: '262.800', y: '232.000', z: '74.500' },
     ov: [ 100, 100, 100 ],
     subState: 0,
     wco: { x: '-302.800', y: '-232.000', z: '-74.500' },
     buf: { planner: 15, rx: 125 },
     feedrate: 0,
     spindle: 0 },
  parserstate:
   { modal:
      { motion: 'G0',
        wcs: 'G54',
        plane: 'G17',
        units: 'G21',
        distance: 'G90',
        feedrate: 'G94',
        spindle: 'M5',
        coolant: 'M9' },
     tool: '0',
     feedrate: '0',
     spindle: '0' } }

Data is updated when I use the web interface to control my CNC. So something is happening.
But the keyboard does not work.
I tried all hidraw0-3 (that is how many there are) but got the same result.

 **bin/cncjs-pendant-keyboardreader --list**

 vendorId: 1133,
 productId: 4119,
 path: '/dev/hidraw2',
 serialNumber: '1017-d5-7c-dd-41',
 manufacturer: 'Logitech',
 product: 'USB Receiver',
 release: 4609,
 interface: 2 }
 vendorId: 1133,
 productId: 16392,
 path: '/dev/hidraw3',
 serialNumber: '4008-78-1d-b7-3d',
 manufacturer: 'Logitech',
 product: 'USB Receiver',
 release: 4609,
 interface: 2 }
 vendorId: 1133,
 productId: 16420,
 path: '/dev/hidraw1',
 serialNumber: '4024-d5-41-17-92',
 manufacturer: 'Logitech',
 product: 'USB Receiver',
 release: 4609,
 interface: 2 }
 vendorId: 1133,
 productId: 50475,
 path: '/dev/hidraw0',
 serialNumber: '',
 manufacturer: 'Logitech',
 product: 'USB Receiver',
 release: 4609,
 interface: 2 }
i@cncjs:~/cncjs-pendant-keyboardreader $

If I run with an illegal hidraw

**bin/cncjs-pendant-keyboardreader --socket-port 8000 --port /dev/ttyACM0 --device /dev/hidraw8**

it shows me this:

Connected to ws://localhost:8000?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IiIsIm5hbWUiOiJjbmNqcy1wZW5kYW50IiwiaWF0IjoxNjEyMDA5NzQ2LCJleHAiOjE2MTQ2MDE3NDZ9.lMJsw5d7w290KBCsLvugV1KZm3yhhYPD1kaFnGjWs1Y
Connected to port "/dev/ttyACM0" (Baud rate: 115200)
/home/pi/cncjs-pendant-keyboardreader/node_modules/node-hid/nodehid.js:49
    this._raw = new (Function.prototype.bind.apply(binding.HID,
                ^

Error: cannot open device with path /dev/hidraw8
    at new HID (/home/pi/cncjs-pendant-keyboardreader/node_modules/node-hid/nodehid.js:49:17)
    at /home/pi/cncjs-pendant-keyboardreader/bin/cncjs-pendant-keyboardreader:148:24
    at Socket.<anonymous> (/home/pi/cncjs-pendant-keyboardreader/index.js:78:9)
    at Socket.Emitter.emit (/home/pi/cncjs-pendant-keyboardreader/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/home/pi/cncjs-pendant-keyboardreader/node_modules/socket.io-client/lib/socket.js:270:10)
    at Socket.onpacket (/home/pi/cncjs-pendant-keyboardreader/node_modules/socket.io-client/lib/socket.js:228:12)
    at Manager.<anonymous> (/home/pi/cncjs-pendant-keyboardreader/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/home/pi/cncjs-pendant-keyboardreader/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/home/pi/cncjs-pendant-keyboardreader/node_modules/socket.io-client/lib/manager.js:332:8)
    at Decoder.<anonymous> (/home/pi/cncjs-pendant-keyboardreader/node_modules/component-bind/index.js:21:15)
pi@cncjs:~/cncjs-pendant-keyboardreader$

**Comment by Billiam** [comment]
Sorry I missed this. While this is probably far to late to help you, maybe it will benefit somebody else.

It looks like the pendant is set up correctly, but your current user doesn't have permission to access the `/dev/hidraw*` usd device, so you'd need to set up `udev` rules so that your user has permission to access the device.
